### ISSUE TITLE
cellvoyager.StackedTile: consider making _paths field public

### ISSUE THREAD

**Issue by imagejan** [fmi-faim/faim-ipa#116]
For our use of `faim_hcs` in `faim-wako-searchfirst` (to assemble tiled first-pass acquisitions), we need to get the path of the first tile (field `F0001`) to derive the name of the `.csv` file.

It would be good to have access to `paths` as a public field, in analogy to `Tile.path`, so we don't have to rely on accessing a private `_paths` field.

(This is of course not blocking me at all, I just file this issue to consider for API stability...)

**Comment by tibuch** [comment]
I am not very happy with how it looks at the moment: `path` vs `_paths` 
Refactoring this part into something consistent would be awesome!

**Comment by imagejan** [comment]
Closing in favor of #118.
