### ISSUE TITLE
Labelling of row/column in HCS

### ISSUE THREAD

**Issue by jeskowagner** [fmi-faim/faim-ipa#130]
Hi!
When working with HCS data, I was wondering whether you had found good way to integrate well (i.e. row/column) information in ome-zarr files when viewed with `napari-ome-zarr`. It would be great to have information available as to which well a user is looking at, e.g. when hovering their mouse over a cell. I recognise you are not responsible for for `napari-ome-zarr`, but was just curious whether you had played around with anything in that area from a user perspective.
Thanks,
Jesko

**Comment by tibuch** [comment]
Hi Jesko,

We are using [MoBIE](https://mobie.github.io/) for ome-zarr plate visualization. It comes with the well ID feature built in and even allows to attach arbitrary tables (e.g. conditions).

Cheers

**Comment by tibuch** [comment]
The zarr created by the Single-Plane example should work with MoBIE > Open > Open HCS Dataset.

![image](https://github.com/fmi-faim/faim-ipa/assets/5450869/cec27285-0882-416c-83dc-125e6f98f23e)

I think it fails if you have trailing `/` after `.zarr`.

**Comment by jeskowagner** [comment]
In case anyone comes across this issue in the future, I resolved the issue relating to `multiscales` by opening the files with the "Open HCS Dataset" option as detailed [here](https://forum.image.sc/t/towards-opening-ome-zarr-hcs-in-fiji/87971/19).
