### ISSUE TITLE
Issue in stitching.stitching_utils.fuse_linear

### ISSUE THREAD

**Issue by fstur** [fmi-faim/faim-ipa#154]
In the fuse_linear function, there is an issue if the overlap region is at the border of the chunk: The weights are then calculated incorrectly. The fuse_linear function is missing some context of adjacent chunks. It's probably easiest to calculate the weights already in the warp_yx function.

https://github.com/fmi-faim/faim-ipa/blob/99a995484d2487aa5bc195e761acc360b18e0d7d/src/faim_hcs/stitching/stitching_utils.py#L10C1-L45C64

**Comment by tibuch** [comment]
Hi @fstur,

Thank you for reporting this bug. Are you already working on a fix?

**Comment by tibuch** [comment]
Awesome! Looking forward to the PR!

**Comment by tibuch** [comment]
Closed by #157.
