### ISSUE TITLE
Created logger does not log INFO level

### ISSUE THREAD

**Issue by tibuch** [fmi-faim/faim-ipa#167]
Something changed with `logging` and our `create_logger` function returns a logger which does not log `INFO` events. Setting `logger.setLevel('INFO')` fixes the issue.

**Comment by imagejan** [comment]
Thanks, I just had noticed this last week as well. It seems we can then remove the redundant setting on the `handler` as it'll only receive messages with the logger's level and above anyway, right?

https://github.com/fmi-faim/faim-ipa/blob/caa6f39ffc5fac0e0f13a1a336d7b6f817e31f15/src/faim_ipa/utils.py#L76

**Comment by tibuch** [comment]
Probably. I did not test what happens if it gets removed.

**Comment by imagejan** [comment]
👍 I opened https://github.com/fmi-faim/faim-ipa/pull/169.
