### ISSUE TITLE
Logging with decorator

### ISSUE THREAD

**Issue by tibuch** [fmi-faim/faim-ipa#179]
Copied from [here](https://github.com/fmi-faim/ipa-project-template/issues/8).
```
my_logger = create_logger(name="processing")

@log(logger=my_logger)
def run_processing(input_dir: str, output_dir: str):
	# do some processing
	my_logger.info("Done!")
```

We should start a example collection to keep track of these tips and tricks!

**Comment by imagejan** [comment]
We decided this pattern (`@log` annotation with custom `logger` to be provided) is too over-engineered for our current use cases.
