### ISSUE TITLE
Deploy to pypi and conda-forge

### ISSUE THREAD

**Issue by tibuch** [fmi-faim/faim-ipa#40]

**Comment by tibuch** [comment]
pypi: https://pypi.org/project/faim-ipa/

**Comment by imagejan** [comment]
I deployed a conda package to the `prefix.dev/fmi-faim` channel:

https://prefix.dev/channels/fmi-faim/packages/faim-ipa

```
micromamba install -c https://repo.prefix.dev/fmi-faim faim-ipa
```

```
pixi project channel add https://repo.prefix.dev/fmi-faim
pixi add faim-ipa
```

---

For now I built the package using `rattler-build` and uploaded manually. We should automate the deployment in the release process once development of `pixi build` and `rattler-build build` and the respective `upload` sub-commands have stabilized.

**Comment by imagejan** [comment]
@tibuch I opened https://github.com/conda-forge/staged-recipes/pull/27213 for conda-forge. Please comment there confirming that you can be co-maintainer 🙂

**Comment by imagejan** [comment]
🚀 `faim-ipa` is now deployed to conda-forge (https://anaconda.org/conda-forge/faim-ipa) via https://github.com/fmi-faim/faim-ipa-feedstock 🎉
