### ISSUE TITLE
ROI tables: Link to specification once available

### ISSUE THREAD

**Issue by jluethi** [fmi-faim/faim-ipa#41]
https://github.com/fmi-faim/faim-hcs/pull/32 proposes to use the Fractal ROI tables in its v1 iteration. Would be great to link to the actual spec for this (see https://github.com/fmi-faim/faim-hcs/pull/32#issuecomment-1719007345).

We're working on a formalized Fractal ROI table v1 spec, it's planned for October. This is just a reminder issue to link to it once available

**Comment by tibuch** [comment]
ROI tables moved out of faim-ipa.
