### ISSUE TITLE
Rework `write_labels_to_group`

### ISSUE THREAD

**Issue by tibuch** [fmi-faim/faim-ipa#64]
We should investigate if this function can be reworked such that the metadata can be directly passed to `write_image`. 

https://github.com/fmi-faim/faim-hcs/blob/001ece955f202b7e97f5e6c57415caec7e108fc2/src/faim_hcs/Zarr.py#L14

**Comment by imagejan** [comment]
Should be upstream somewhere, e.g. in https://github.com/fractal-analytics-platform/ngio.
