### ISSUE TITLE
Create 3D Tile for CV and MD acquisitions

### ISSUE THREAD

**Issue by tibuch** [fmi-faim/faim-ipa#83]
The `DaskTileStitcher` now supports 3D data. We could reduce the computation graph for 3D stitching by introducing a `Tile` that loads multiple z-planes and assembles them into a 3D image. This could lead to faster stitching of 3D (ZYX) data.

**Comment by tibuch** [comment]
There is now a `[StackedTile](https://github.com/fmi-faim/faim-hcs/blob/main/src/faim_hcs/hcs/cellvoyager/StackedTile.py)` for the CV data.

**Comment by imagejan** [comment]
See also #118.
